<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="resume" nsURI="http://model.waweb.io/drkstr101/resume" nsPrefix="drkstr101.resume">
  <eClassifiers xsi:type="ecore:EClass" name="Resume">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skillsByName" lowerBound="1"
        eType="#//SkillsByName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accomplishments" upperBound="-1"
        eType="#//Accomplishment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employers" upperBound="-1"
        eType="#//Employment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkillsByName" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Skill"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Skill">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Skill" containment="true" eOpposite="#//Skill/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Skill"
        eOpposite="#//Skill/children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="employer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//EmploymentType"
        defaultValueLiteral="DirectW2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accomplishments" eType="#//Accomplishment"
        eOpposite="#//Accomplishment/employment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Accomplishment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employment" eType="#//Employment"
        eOpposite="#//Employment/accomplishments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skills" upperBound="-1"
        eType="#//Skill"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EmploymentType">
    <eLiterals name="DirectW2" literal="DirectW2"/>
    <eLiterals name="Direct1099" value="1" literal="Direct1099"/>
    <eLiterals name="CorpToCorp" value="2" literal="CorpToCorp"/>
    <eLiterals name="Self" value="3" literal="Self"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccomplishmentType">
    <eLiterals name="Academic" literal="Academic"/>
    <eLiterals name="Professional" value="1" literal="Professional"/>
    <eLiterals name="Personal" value="2"/>
    <eLiterals name="Volunteer" value="3"/>
  </eClassifiers>
</ecore:EPackage>
