{
  "formatVersion": "1.1",
  "component": {
    "group": "drkstr101.resume",
    "module": "gradle-resume",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "jlpk4atfwvcfnk5lfa46skjasy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-resume-1.0.0.jar",
          "url": "gradle-resume-1.0.0.jar",
          "size": 126477,
          "sha512": "5530597d347c258b7989bdf28fcb20c07f6f06ec9415f9b0056d62a17046cfb3be02b31c13190191c66f79a8adb5c36092faea2c7ffa294a673002c3d6c61b85",
          "sha256": "5a2c5c6490e0e9d57c44cc3ba56152b78893c348d8b010cae17dcc87aaf3bd1c",
          "sha1": "acbab98086ea85ee60a272e561c18d24825350bb",
          "md5": "d7fa4f1b183bce4c165c7efc90da1f31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "drkstr101.resume",
          "module": "kumo-core",
          "version": {
            "requires": "1.28.0"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark",
          "version": {
            "requires": "0.62.2"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-ext-tables",
          "version": {
            "requires": "0.62.2"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-ext-definition",
          "version": {
            "requires": "0.62.2"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-ext-gfm-strikethrough",
          "version": {
            "requires": "0.62.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-resume-1.0.0.jar",
          "url": "gradle-resume-1.0.0.jar",
          "size": 126477,
          "sha512": "5530597d347c258b7989bdf28fcb20c07f6f06ec9415f9b0056d62a17046cfb3be02b31c13190191c66f79a8adb5c36092faea2c7ffa294a673002c3d6c61b85",
          "sha256": "5a2c5c6490e0e9d57c44cc3ba56152b78893c348d8b010cae17dcc87aaf3bd1c",
          "sha1": "acbab98086ea85ee60a272e561c18d24825350bb",
          "md5": "d7fa4f1b183bce4c165c7efc90da1f31"
        }
      ]
    }
  ]
}
