/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package drkstr101.resume.plugin

import org.gradle.testfixtures.ProjectBuilder

import drkstr101.resume.plugin.model.Resume
import spock.lang.Specification

/**
 * A simple unit test for the 'drkstr101.resume.plugin.greeting' plugin.
 */
public class ModelProviderTest extends Specification {
	def canProvideResumeModel() {
		given:
		def project = ProjectBuilder.builder().build()
		def newInstance = project.objects.&newInstance

		ResumeExtension resume = newInstance(ResumeExtension)
		resume.skills << newInstance(SkillExtension, "sk1")
		resume.skills << newInstance(SkillExtension, "sk2")
		
		resume.references << newInstance(ReferenceExtension, "ref1")
		resume.references << newInstance(ReferenceExtension, "ref2")
		
		resume.accomplishments << newInstance(AccomplishmentExtension, "aca")
				.tap { skills = ['sk1']; references = ['ref1', 'ref2'] }
		resume.accomplishments << newInstance(AccomplishmentExtension, "acb")
				.tap { skills = ['sk1', 'sk2']; references = ['ref2'] }
		resume.accomplishments << newInstance(AccomplishmentExtension, "acc")
			.tap { skills = ['sk2'] }
		
		resume.employers << newInstance(EmploymentExtension, "ema")
				.tap { accomplishments = ['aca'] }
		resume.employers << newInstance(EmploymentExtension, "emb")
				.tap { accomplishments = ['acb'] }
		
		when:
		Resume model = new ResumeModelProvider(resume).get()

		then:
		assert model != null
		
		// Assert skills
		assert !model.skills.isEmpty()
		assert model.skills.get('sk1').name == "sk1"
		assert model.skills.get('sk2').name == "sk2"
		
		// Assert references
		assert !model.references.isEmpty()
		assert model.references.get('ref1').name == "ref1"
		assert model.references.get('ref2').name == "ref2"
		
		// Assert accomplishments
		assert !model.accomplishments.isEmpty()
		assert model.accomplishments.get('aca').name == "aca"
		assert model.accomplishments.get('aca')
				.skills
				.collect({ it.name }) == ["sk1"]
		assert model.accomplishments.get('aca')
				.references
				.collect({ it.name }) == ["ref1", "ref2"]
				
		assert model.accomplishments.get('acb').name == "acb"
		assert model.accomplishments.get('acb')
				.skills
				.collect({ it.name }) == ["sk1", "sk2"]
		assert model.accomplishments.get('acb')
				.references
				.collect({ it.name }) == ["ref2"]
		
		assert model.accomplishments.get('acc').name == "acc"
		assert model.accomplishments.get('acc')
				.skills
				.collect({ it.name }) == ["sk2"]
		assert model.accomplishments.get('acc')
				.references.isEmpty()
			
		
		// Assert employers
		assert !model.employers.isEmpty()
		assert model.employers.get('ema')
				.accomplishments
				.collect({ it.name }) == ["aca"]
		assert model.employers.get('emb')
				.accomplishments
				.collect({ it.name }) == ["acb"]
	}
}
