/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package drkstr101.resume.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
public class ResumePlugin implements Plugin<Project> {
    public void apply(Project project) {
        final ResumeExtension resume = project.extensions.create('resume', ResumeExtension)
		assert resume
		
		// Add a task to validate all input data
        project.tasks.register("validateResume") {
            doLast {
                assert resume.skillDataFile.exists()
                assert resume.employerDataFile.exists()
            }
        }
    }
}
