{
  "formatVersion": "1.1",
  "component": {
    "group": "drkstr101.resume",
    "module": "gradle-resume",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "n76d5mg5ajf7plgj2vhq3pqauy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-resume-1.0.1.jar",
          "url": "gradle-resume-1.0.1.jar",
          "size": 126502,
          "sha512": "ad65c2014659c9b3192cdf916c81ab6e394c94336b22102f5b52832a7bc4fd7456fd7ff967046a986036b61091107cb138f7c647c0aa846d62609d1ce08029ec",
          "sha256": "b9dfb6f48229e031d3efebcef046a1c7d85be5a4441098daef4fa7b592ede5a8",
          "sha1": "7bbe15f5f322383cdd7246cf71d33a6be7f1a6c7",
          "md5": "627fbf41edf57f6dc4aebbefea9afa4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "drkstr101.resume",
          "module": "kumo-core",
          "version": {
            "requires": "1.28.0"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark",
          "version": {
            "requires": "0.62.2"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-ext-tables",
          "version": {
            "requires": "0.62.2"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-ext-definition",
          "version": {
            "requires": "0.62.2"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-ext-gfm-strikethrough",
          "version": {
            "requires": "0.62.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-resume-1.0.1.jar",
          "url": "gradle-resume-1.0.1.jar",
          "size": 126502,
          "sha512": "ad65c2014659c9b3192cdf916c81ab6e394c94336b22102f5b52832a7bc4fd7456fd7ff967046a986036b61091107cb138f7c647c0aa846d62609d1ce08029ec",
          "sha256": "b9dfb6f48229e031d3efebcef046a1c7d85be5a4441098daef4fa7b592ede5a8",
          "sha1": "7bbe15f5f322383cdd7246cf71d33a6be7f1a6c7",
          "md5": "627fbf41edf57f6dc4aebbefea9afa4a"
        }
      ]
    }
  ]
}
